apiVersion: v1
kind: Service
metadata:
  name: db # it should be as db as worker service accepts database name as db, any other name will lead to failure of connection between worker and database
  labels:
    name: db-service
    app:  demo-voting-app
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: db-pod
    app: demo-voting-app